---
title: "Final table"
author: "Beks"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
```

```{r include=FALSE}
read_complete = read.csv(file = "~/SIVIOgit/clean_financial_inclusion.csv")
```

```{r}
read_complete %>%
  select(industry, X.2, X.3, X.4, X.5, X.6, X.7, X.8, X.9, X.10, X.11, X.12, X.13, X.14, X.15, X.16, X.17, X.18, X.19, X.20) %>%
  filter(X.20 != "" & (industry != "" | X.2 != "" | X.3 != "" | X.4 != "" | X.5 != "" | X.6 != "" | X.7 != "" | X.8 != "" | X.9 != "" | X.10  != "" | X.11 != "" | X.12 != "" | X.13 != "" | X.14 != "" | X.15 != "" | X.16 != "" | X.17 != "" | X.18 != "" | X.19 != "")) %>%
  pivot_longer(cols = c(industry, X.2, X.3, X.4, X.5, X.6, X.7, X.8, X.9, X.10, X.11, X.12, X.13, X.14, X.15, X.16, X.17, X.18, X.19), names_to = "industry", values_to = "sector") %>%
  filter( sector != "") %>%
  select(-c(industry))

read_complete %>%
  select(funds_start, X.25, X.26, X.27, X.28, X.29, X.30, X.31, X.32, X.33, X.34, X.35, X.36, X.37) %>%
  filter(X.37 != "" & (funds_start != "" | X.25 != "" | X.26 != "" | X.27 != "" | X.28 != "" | X.29 != "" | X.30 != "" | X.31 != "" | X.32 != "" | X.33 != "" | X.34 != "" | X.35 != "" | X.36 != "" )) %>%
  pivot_longer(cols = c(funds_start, X.25, X.26, X.27, X.28, X.29, X.30, X.31, X.32, X.33, X.34, X.35, X.36),
               names_to = "funds", values_to = "start") %>%
  filter(start != "") %>%
  select(-c(funds))

read_complete %>%
  select(funds_ongoing, X.45, X.46, X.47, X.48, X.49, X.50, X.51, X.52, X.53, X.54, X.55, X.56, X.57, X.58) %>%
  filter(X.58 != "" & (funds_ongoing != "" | X.45 != "" | X.46 != "" | X.47 != "" | X.48 != "" | X.49 != "" | X.50 != "" | X.51 != "" | X.52 != "" | X.53 != "" | X.54 != "" | X.55 != "" | X.56 != "" | X.57 != "" )) %>%
  pivot_longer(cols = c(funds_ongoing, X.45, X.46, X.47, X.48, X.49, X.50, X.51, X.52, X.53, X.54, X.55, X.56, X.57), names_to = "funds", values_to = "ongoing") %>%
  filter(ongoing != "") %>%
  select(-c(funds))
```


# clean up data

- pivot longer columns with multiple select
- summarize so as to rename other options
- categorize the other variables
- pivot wider so as to do table analysis break down of each type

```{r}
financial_inclusion_survey = read_complete %>%
  
  # business sector/industry
  mutate(X.20 = trimws(X.20)) %>%
  pivot_longer(cols = c(industry, 
                        X.2, X.3, X.4, X.5, X.6, X.7, X.8, X.9, X.10, X.11, X.12, X.13, X.14, X.15, X.16, X.17, X.18, X.19, X.20),
               names_to = "survey_industry",
               values_to = "industry_sector") %>%
  filter(industry_sector != "Other (please specify)",
         industry_sector != "") %>%
  select(-(survey_industry)) %>%
  mutate(single_count = 1) %>%
  # categorize the other sectors under our labels
  # mutate(industry_sector = case_when(
  #   industry_sector == "Welding" ~ "Construction Energy, Water and Architecture",
  #   industry_sector == "Waste recycling" ~ "Construction Energy, Water and Architecture",
  #   industry_sector == "Small farmer" ~ "Agriculture, hunting , forestry and fishing.",
  #   industry_sector == "Selling cellphones and repairing cellphones" ~ "-",
  #   industry_sector == "Security Services" ~ "",
  #   industry_sector == "Satellite and visuals" ~ "Information and Communication Technology",
  #   industry_sector == "Saloon and barber" ~ "Trichology and cosmetology (hair, makeup, nails and beauty therapy)",
  #   industry_sector == "Running a bar" ~ "Tourism accommodation and Restaurants",
  #   industry_sector == "REAL ESTATE VALUATIONS" ~ "",
  #   industry_sector == "PRINTING" ~ "Graphics, Technical design, computer software and Printing",
  #   industry_sector == "Poultry and baking cream dorghnuts" ~ "Catering, baking and culinary arts", 
  #   # industry_sector == "Poultry" ~ "Agriculture, hunting , forestry and fishing.", 
  #   industry_sector == "PHONES" ~ "", 
  #   industry_sector == "Motor Spares and Accessories" ~ "", 
  #   industry_sector == "motor mechanic" ~ "", 
  #   industry_sector == "Mechanics" ~ "", 
  #   industry_sector == "Lodge bed only" ~ "Tourism accommodation and Restaurants", 
  #   industry_sector == "Liqour outlet" ~ "Retail and wholesale", 
  #   industry_sector == "Importing services shipping" ~ "", 
  #   industry_sector == "ICE CREAM COURTENIER RESALER" ~ "", 
  #   industry_sector == "Hydraulics and pneumatics and diesel tech" ~ "", 
  #   industry_sector == "Hardware stores" ~ "Retail and wholesale", 
  #   industry_sector == "Hardware store" ~ "Retail and wholesale", 
  #   industry_sector == "Hardware and construction" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "Hardware and butchery" ~ "", 
  #   industry_sector == "Hardware" ~ "", 
  #   industry_sector == "Grocery shop" ~ "Retail and wholesale", 
  #   industry_sector == "Grocery and cooking sadza" ~ "Catering, baking and culinary arts", 
  #   industry_sector == "Grinding meal" ~ "Catering, baking and culinary arts", 
  #   industry_sector == "General dealer" ~ "Retail and wholesale", 
  #   # industry_sector == "Furniture" ~ "Manufacturing", 
  #   industry_sector == "Fruits, airtime and selling money" ~ "", 
  #   industry_sector == "Fruits and vegetables" ~ "Agriculture, hunting , forestry and fishing.", 
  #   industry_sector == "FASHION" ~ "Textile, apparel, leather", 
  #   industry_sector == "Engineering" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "Energy" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "electrician" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "Electrical hardware" ~ "", 
  #   industry_sector == "Earthmoving" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "Driving school" ~ "", 
  #   industry_sector == "Croos boarder trading" ~ "", 
  #   industry_sector == "Cooking sadza" ~ "Catering, baking and culinary arts", 
  #   industry_sector == "Construction" ~ "Construction Energy, Water and Architecture", 
  #   industry_sector == "CLOTHING SHOP" ~ "Retail and wholesale", 
  #   industry_sector == "Clothing" ~ "Textile, apparel, leather", 
  #   industry_sector == "Chicken poultry" ~ "Agriculture, hunting , forestry and fishing.", 
  #   industry_sector == "Cell phones and accessories" ~ "Retail and wholesale", 
  #   # industry_sector == "Carpentry" ~ "Manufacturing", 
  #   industry_sector == "Car sales" ~ "Retail and wholesale", 
  #   industry_sector == "Cake making" ~ "Catering, baking and culinary arts", 
  #   industry_sector == "Butchery" ~ "", 
  #   industry_sector == "Butcher" ~ "",
  #   industry_sector == "Bottle store" ~ "Retail and wholesale", 
  #   industry_sector == "Beerhall" ~ "Tourism accommodation and Restaurants", 
  #   industry_sector == "Beer hall" ~ "Tourism accommodation and Restaurants", 
  #   industry_sector == "Barbershop" ~ "Trichology and cosmetology (hair, makeup, nails and beauty therapy)", 
  #   industry_sector == "Bar" ~ "Tourism accommodation and Restaurants", 
  #   industry_sector == "Automotive" ~ "",
  #   TRUE ~ as.character(industry_sector),
  # )) %>%
  filter(industry_sector != "") %>%
  pivot_wider(names_from = industry_sector,
              values_from = single_count) %>%
  rename(sector_manufacturing = Manufacturing,
         sector_mining = `Mining and quarrying`,
         sector_vending = `Vending (tuck-shop/flea market)`,
         sector_agriculture = `Agriculture, hunting , forestry and fishing.`,
         sector_retail = `Retail and wholesale`,
         sector_tourism = `Tourism accommodation and Restaurants`,
         sector_professional = `Professional, Consulting, Scientific and Technical Activities`,
         sector_handicrafts = Handicrafts,
         sector_trichology = `Trichology and cosmetology (hair, makeup, nails and beauty therapy)`,
         sector_construction = `Construction Energy, Water and Architecture`,
         sector_logistics = `Logistics and transport`,
         sector_education = Education,
         sector_graphics = `Graphics, Technical design, computer software and Printing`,
         sector_textile = `Textile, apparel, leather`,
         sector_ict = `Information and Communication Technology`,
         sector_catering = `Catering, baking and culinary arts`,
         sector_arts = `Arts, culture, sport, events, media, and entertainment`,
         sector_health = `Health and social services`,
         sector_financial = `Financial services and insurance`,
         ) %>%
  
  # funds to start
  mutate(X.20 = trimws(X.37)) %>%
  pivot_longer(cols = c(funds_start, X.25, X.26, X.27, X.28, X.29, X.30, X.31, X.32, X.33, X.34, X.35, X.36, X.37),
               names_to = "survey_funds_start",
               values_to = "funds_start") %>%
  filter(funds_start != "Other (please specify)",
         funds_start != "") %>%
  select(-(survey_funds_start)) %>%
  mutate(single_count1 = 1) %>%
  # mutate(funds_start = case_when(
  #   funds_start == "Sold property" |
  #   # funds_start == "Political party funds" |
  #   # funds_start == "Pension funds" |
  #   funds_start == "pension benefits" |
  #   funds_start == "No funds were needed since I just used my hands to plait" ~ "Personal savings (from salary or other business initiatives)",
  #   funds_start == "Mukando" ~ "",
  #   funds_start == "Mikando" ~ "",
  #   funds_start == "LOAN" ~ "",
  #   TRUE ~ as.character(funds_start),
  # )) %>%
  filter(funds_start != "") %>%
  pivot_wider(names_from = funds_start,
              values_from = single_count1) %>% 
  rename(start_savings = `Personal savings (from salary or other business initiatives)`,
         start_chimbadzo = `Loan sharks (chimbadzo)`,
         start_familylocal = `Locally based Family and friends`,
         start_banks = Banks,
         start_remittances = `Remittances from family or friends outside Zimbabwe`,
         start_colleagues = `Fellow business colleagues`,
         start_rosals = `Rotating and savings groups`,
         start_localngo = `Local NGOs`,
         start_mfi = `Microfinance institution`,
         start_grant = `International organization through a grant`,
         start_govt = `Government assistance programs`,
         start_creditunion = `Credit unions`) %>%
  
  
  # funds for ongoing business
  # not a required question... so some responses can be blank but a pivot longer will produce multiple blanks so have to group then pivot wider
  # create new variable with not specified so as to keep same filtering as above methods
  mutate(funds_ongoing_not_specified = ifelse(
    (funds_ongoing == "" & X.45 == "" &  X.46 == "" & X.47 == "" & X.48 == "" & X.49 == "" & X.50 == "" & X.51 == "" & X.52 == "" & X.53 == "" & X.54 == "" & X.55 == "" & X.56 == "" & X.57 == "" & X.58 == ""), "funds_ongoing_not_specified", "" ),
    X.58 = trimws(X.58)
    ) %>%
  pivot_longer(cols = c(funds_ongoing, X.45, X.46, X.47, X.48, X.49, X.50, X.51, X.52, X.53, X.54, X.55, X.56, X.57, X.58, funds_ongoing_not_specified),
               names_to = "survey_funds_ongoing",
               values_to = "funds_ongoing") %>%
  filter(funds_ongoing != "Other (please specify)",
         funds_ongoing != ""
         ) %>%
  select(-(survey_funds_ongoing)) %>%
  mutate(single_count2 = 1) %>%
  # mutate(funds_ongoing = case_when(
  #     funds_ongoing == "Business funds" |
  #     funds_ongoing == "Business is self sponsored" |
  #     # funds_ongoing == "Business profits" |
  #     # funds_ongoing == "Business returns" |
  #     # funds_ongoing == "Clients pay deposit to fund initial project implementation costs" |
  #     funds_ongoing == "From business" |
  #     funds_ongoing == "From my profits" |
  #     funds_ongoing == "From the profits" |
  #     funds_ongoing == "From the takeaway" |
  #     funds_ongoing == "I use profit from last batch" |
  #     funds_ongoing == "My profits" |
  #     # funds_ongoing == "Personal savings" |
  #     # funds_ongoing == "Profit" |
  #     # funds_ongoing == "Profit from farming" |
  #     funds_ongoing == "Reimbursement of profits" |
  #     funds_ongoing == "Salon" |
  #     # funds_ongoing == "Self financing projects" |
  #     funds_ongoing == "The business" |
  #     funds_ongoing == "The business itself" |
  #     funds_ongoing == "Trade" |
  #     # funds_ongoing == "We get deposit when starting a project which we use to meet the project costs" ~ "Personal savings (from salary or other business initiatives)",
  #     funds_ongoing == "Mikando" ~ "",
  #     funds_ongoing == "Mukando" ~ "",
  #     TRUE ~ as.character(funds_ongoing),
  #   )) %>%
  filter(funds_ongoing != "")  %>%
  pivot_wider(names_from = funds_ongoing,
              values_from = single_count2) %>%
  rename(ongoing_savings = `Personal savings (from salary or other business initiatives)`,
         ongoing_chimbadzo = `Loan sharks (chimbadzo)`,
         ongoing_familylocal = `Locally based family and friends`,
         ongoing_banks = Banks,
         ongoing_remittances = `Remittances from family or friends outside Zimbabwe`,
         ongoing_colleagues = `Fellow business colleagues`,
         ongoing_rosals = `Rotating and Savings Groups`,
         ongoing_localngo = `Local NGOs`,
         ongoing_mfi = `Microfinance institutions`,
         ongoing_grant = `International organization through a grant`,
         ongoing_govt = `Government of Zimbabwe`,
         ongoing_creditunion = `Credit unions`,
         ongoing_orderfinance = `Order finance companies`,
         ) %>%
  mutate(total_responses = 1)
```

# gather entries to rename and then fit into other categories

```{r}
# inclusion_survey %>%
#   group_by(industry_sector) %>%
#   summarise(n=n())
# 
# inclusion_survey %>%
#   group_by(funds_start) %>%
#   summarise(n=n())
# 
# inclusion_survey %>%
#   group_by(funds_ongoing) %>%
#   summarise(n=n())
```

# sum

```{r}
summed_percentages = financial_inclusion_survey %>%
  group_by(province) %>%
  summarise_if(is.numeric, sum, na.rm = TRUE) %>%
  group_by(province) %>%
  summarise(total_responses = total_responses,
            
            # percentage women and men owners
            percent_female_owner = (female_owner/total_responses) * 100,
            percent_male_owner = (male_owner/total_responses) * 100,
            
            # highest level of education of owner
            percent_primary = (primary/total_responses) * 100,
            percent_secondary = (secondary/total_responses) * 100,
            percent_tertiary = (tertiary/total_responses) * 100,
            percent_vocational = (vocational/total_responses) * 100,
            
            # urban rural distribution
            percent_urban = (urban/total_responses) * 100,
            percent_rural = (rural/total_responses) * 100,
            
            # micro small medium distribution
            percent_micro = (micro/total_responses) * 100,
            percent_small = (small/total_responses) * 100,
            percent_medium = (medium/total_responses) * 100,
            
            # sector distribution... same repetitive code... should try to code a loop???
            percent_manufacturing = (sector_manufacturing/total_responses) *100,
            percent_retail = (sector_retail/total_responses) *100,
            percent_agriculture = (sector_agriculture/total_responses) *100,
            percent_mining = (sector_mining/total_responses) *100,
            percent_vending = (sector_vending/total_responses) *100,
            percent_health = (sector_health/total_responses) *100,
            percent_construction = (sector_construction/total_responses) *100,
            percent_education = (sector_education/total_responses) *100,
            percent_catering = (sector_catering/total_responses) *100,
            percent_ict = (sector_ict/total_responses) *100,
            percent_professional = (sector_professional/total_responses) *100,
            percent_arts = (sector_arts/total_responses) *100,
            percent_logistics = (sector_logistics/total_responses) *100,
            percent_financial = (sector_financial/total_responses) *100,
            percent_textile = (sector_textile/total_responses) *100,
            percent_handicrafts = (sector_handicrafts/total_responses) *100,
            percent_tourism = (sector_tourism/total_responses) *100,
            percent_trichology = (sector_trichology/total_responses) *100,
            percent_graphics = (sector_graphics/total_responses) *100,
            
            # access bank
            percent_bank_account = (bank_account_logic/total_responses) *100,
            
            # mobile money
            percent_mobile_account = (mobile_account_logic/total_responses) *100,
            percent_mobile_insurance = (mobile_insurance_logic/total_responses) *100,
            
            # registration
            percent_registered = (registration_logic/total_responses) * 100,
            percent_zimra = (zimra_register_logic/total_responses) * 100,
            
            # insurance
            percent_insurance = (insurance_logic/total_responses) *100,
            
            # pensions
            percent_pension_policy = (pension_logic/total_responses) *100,
            
            # savings
            percent_saving_facility = (savings_logic/total_responses) *100,
            
            # loans to start up
            percent_savings_start = (start_savings/total_responses) *100,
            percent_chimbadzo_start = (start_chimbadzo/total_responses) *100,
            percent_familylocal_start = (start_familylocal/total_responses) *100,
            percent_banks_start = (start_banks/total_responses) *100,
            percent_remittance_start = (start_remittances/total_responses) *100,
            percent_collegues_start = (start_colleagues/total_responses) *100,
            percent_rosals_start = (start_rosals/total_responses) *100,
            percent_localngo_start = (start_localngo/total_responses) *100,
            percent_mfi_start = (start_mfi/total_responses) *100,
            percent_grant_start = (start_grant/total_responses) *100,
            percent_govt_start = (start_govt/total_responses) *100,
            percent_creditunion_start = (start_creditunion/total_responses) *100,
            
            # loans for ongoing business
            percent_savings_ongoing = (ongoing_savings/total_responses) *100,
            percent_chimbadzo_ongoing = (ongoing_chimbadzo/total_responses) *100,
            percent_familylocal_ongoing = (ongoing_familylocal/total_responses) *100,
            percent_banks_ongoing = (ongoing_banks/total_responses) *100,
            percent_remittance_ongoing = (ongoing_remittances/total_responses) *100,
            percent_collegues_ongoing = (ongoing_colleagues/total_responses) *100,
            percent_rosals_ongoing = (ongoing_rosals/total_responses) *100,
            percent_localngo_ongoing = (ongoing_localngo/total_responses) *100,
            percent_mfi_ongoing = (ongoing_mfi/total_responses) *100,
            percent_grant_ongoing = (ongoing_mfi/total_responses) *100,
            percent_govt_ongoing = (ongoing_govt/total_responses) *100,
            percent_creditunion_ongoing = (ongoing_creditunion/total_responses) *100,
            percent_orderfinance_ongoing = (ongoing_orderfinance/total_responses) *100,
            
            ) %>%
  mutate_if(is.numeric, round, 2)

summed_percentages
```

# Averages

```{r}
averages = financial_inclusion_survey %>%
  group_by(province) %>%
  summarise(# average size of business by number of employees
            average_num_employees = mean(num_employees, na.rm = T),
            
            # average size of business by revenue
            average_annual_turnover = mean(annual_turnover, na.rm = T),
            
            # average size of business by assets
            average_gross_assets = mean(gross_assets, na.rm = T),
  ) %>%
  mutate_if(is.numeric, round, 2) %>%
  mutate(enterprise_category = ifelse(average_num_employees <= 5 & 
                               average_gross_assets <= 10000 & 
                               average_annual_turnover <= 30000, 
                             "micro", 
                             ifelse(average_num_employees <= 30 & average_num_employees > 5 &
                                      average_gross_assets <= 250000 & average_gross_assets > 30000 &
                                      average_annual_turnover <= 50000 & average_annual_turnover > 30000, 
                                    "small",
                                    ifelse(average_num_employees <= 75 & average_num_employees > 30 &
                                             average_gross_assets <= 500000 & average_gross_assets > 250000 &
                                             average_annual_turnover <= 500000 & average_annual_turnover > 50000, 
                                           "medium",
                                           "other"))),
         points = 0,
         points = case_when(
           average_num_employees < 5 ~ points+1,
           average_num_employees < 30 ~ points+2,
           average_num_employees < 75 ~ points+3,
           TRUE ~ points+4
         ),
         points = case_when(
           average_gross_assets < 10000 ~ points+1,
           average_gross_assets < 250000 ~ points+2,
           average_gross_assets < 500000 ~ points+3,
           TRUE ~ points+4
         ),
         points = case_when(
           average_annual_turnover < 30000 ~ points+1,
           average_annual_turnover < 50000 ~ points+2,
           average_annual_turnover < 1000000 ~ points+3,
           TRUE ~ points+4
         )) %>%
  mutate(enterprise_category = ifelse(enterprise_category == "other" & points <= 4, "micro",
                             ifelse(enterprise_category == "other" & points <= 7 & points >= 5, "small",
                                    ifelse(enterprise_category == "other" & points <= 9 & points >= 8, "medium", enterprise_category)))
         )
averages
```

# Day to open

```{r}
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}
```

```{r}
days = financial_inclusion_survey %>%
  filter(time_open_bank_account != "",
         time_open_mobile_money_account != "") %>%
  group_by(province) %>%
  summarise(mode_days_open_bank = getmode(time_open_bank_account),
            mode_days_open_mobile = getmode(time_open_mobile_money_account))
days
```

# Select Variables

```{r}
final_table = summed_percentages %>%
  left_join(averages, by = "province") %>%
  left_join(days, by = "province") %>%
  select(province,
         total_responses,
         
         percent_female_owner, percent_male_owner,
         
         percent_primary, percent_secondary, percent_tertiary, percent_vocational,
         
         average_num_employees,
         average_annual_turnover,
         average_gross_assets,
         enterprise_category,
         
         percent_rural, percent_urban,
         
         percent_micro, percent_small, percent_medium,
         
         percent_manufacturing, percent_retail, percent_agriculture, percent_mining,
         percent_vending, percent_health, percent_construction, percent_education,
         percent_catering, percent_ict, percent_professional, percent_arts,
         percent_logistics, percent_financial, percent_textile, percent_handicrafts,
         percent_tourism, percent_trichology, percent_graphics,
         
         percent_bank_account,
         mode_days_open_bank,
         
         percent_mobile_account,
         mode_days_open_mobile,
         percent_mobile_insurance,
         
         percent_registered,
         percent_zimra,
         
         percent_insurance,
         percent_pension_policy,
         percent_saving_facility,
         
         
         percent_savings_start, percent_chimbadzo_start, percent_familylocal_start,
         percent_banks_start, percent_remittance_start, percent_collegues_start,
         percent_rosals_start, percent_localngo_start, percent_mfi_start,
         percent_grant_start, percent_govt_start, percent_creditunion_start,
         
         percent_savings_ongoing, percent_chimbadzo_ongoing, percent_familylocal_ongoing,
         percent_banks_ongoing, percent_remittance_ongoing, percent_collegues_ongoing,
         percent_rosals_ongoing, percent_localngo_ongoing, percent_mfi_ongoing,
         percent_grant_ongoing, percent_govt_ongoing, percent_creditunion_ongoing,
         percent_orderfinance_ongoing,
         )
```

```{r}
write.csv(final_table, file = "~/SIVIOgit/final_province_summary.csv")
```

```{r}
final_table %>%
  kable() %>%
  kable_styling()
```

