---
title: "Complete Progress of Survey Responses"
author: "Centre for Entrepreneurship and Financial Inclusion"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(kableExtra)
```

# date: `r date()`

```{r include=FALSE}
completedata = read.csv(file = "~/SIVIOgit/survey_financial_inclusion.csv", header = T, sep = ",")
```

```{r include=FALSE}
provincecodes = c("hre", "bul", "msc", "msw", "mse", "mas", "mtn", "mts", "mid", "man")
# might have to add blu for bulawayo as common error??
```

```{r correct codes, include=FALSE}
clean_complete = completedata %>%
  filter(substr(standardcode, 1, 3) %in% provincecodes,
         substr(standardcode, 4, 4) %in% c("u", "r")
         )
```

```{r province per enumerators, echo=FALSE}
lastrow = clean_complete %>%
  group_by(province, short_name) %>% 
  summarise(n=n()) %>% 
  nrow() + 1

clean_complete %>%
  group_by(province, short_name) %>%
  distinct() %>%
  summarise(responses = n(),
            urban_reponses = sum(urban),
            rural_responses = sum(rural),
            micro_enterprises = sum(micro),
            small_enterprises = sum(small),
            medium_enterprises = sum(medium)
  ) %>%
  arrange(province) %>%
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(.) else "total")) %>%
  kable(align = 'lccccc') %>%
  kable_styling() %>%
  row_spec(lastrow:(lastrow+9), background = 'grey', bold = T)
```

```{r responses per enumerator, echo=FALSE}
lastrow_name = clean_complete %>% 
  group_by(short_name) %>% 
  summarise(n=n()) %>% 
  nrow() + 1

clean_complete %>%
  group_by(short_name) %>%
  distinct() %>%
  summarise(responses = n(),
            urban_reponses = sum(urban, na.rm = T),
            rural_responses = sum(rural, na.rm = T),
            micro_enterprises = sum(micro, na.rm = T),
            small_enterprises = sum(small, na.rm = T),
            medium_enterprises = sum(medium, na.rm = T)
  ) %>%
  arrange(short_name) %>%
  bind_rows(summarise_all(., ~if(is.numeric(.)) sum(., na.rm = T) else "total")) %>%
  kable(align = 'lccccc') %>%
  kable_styling() %>%
  row_spec(lastrow_name, background = 'grey', bold = T)
```

# Incorrect codes...

Can manually add them to the data cleaning if fix on our end...

If unable to fix then contact enumerators to figure it out 

Or just remove from analysed data

```{r Incorrect codes, echo=FALSE}
completedata %>%
  filter(!(Respondent.ID %in% clean_complete$Respondent.ID)) %>%
  select(standardcode, enumerator_name, Respondent.ID, urbanrural, province, enterprise)
```

# Duplicated Code

Will need to study this section to figure out what responses to remove

And or if it is just duplicate codes.

```{r duplicate, echo=FALSE}
clean_complete %>%
  filter(duplicated != "single")  %>%
  arrange(standardcode) %>%
  select(enumerator_name, standardcode, gender_owner, age_owner, education_owner, province, urbanrural, year_established) %>%
  kable()
```
