---
title: "formality"
author: "Beks"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
```

```{r}
# index = read.csv(file = "~/SIVIOgit/FI_index/index_dimensions.csv")
# 
# write.csv(index, file = "~/SIVIOgit/FI_index/index_formality.csv")
```

```{r}
index_formality = read.csv(file = "~/SIVIOgit/FI_index/index_formality.csv")
index_formality %>%
  head() %>%
  kable()
```

```{r}
index_formality %>%
  ggplot(mapping = aes(x=province, y=index_percentage, fill=formality_inclusion)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle=90, ))
```

```{r}
index_formality %>%
  ggplot(mapping = aes(x=province, y=barriers_percentage, fill=formality_inclusion)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle=90, ))
```

```{r}
index_formality %>%
  ggplot(mapping = aes(x=province, y=compliance_percentage, fill=formality_inclusion)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle=90, ))
```

```{r}
index_formality %>%
  ggplot(mapping = aes(x=province, y=availability_percentage, fill=formality_inclusion)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle=90, ))
```

```{r}
index_formality %>%
  ggplot(mapping = aes(x=province, y=usage_percentage, fill=formality_inclusion)) +
  geom_col(position = "dodge") +
  theme(axis.text.x = element_text(angle=90, ))
```




